package com.mychhachh.app.ui.components

import androidx.compose.material3.LocalTextStyle
import androidx.compose.material3.Text as MaterialText
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextLayoutResult
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.TextUnit

object AppLanguage {
    var current by mutableStateOf("en")
        private set

    val isUrdu: Boolean
        get() = current == "ur"

    private val urdu = mapOf(
        "Request for Blue Tick" to "بلیو ٹک کی درخواست",
        "Total Users" to "کل یوزرز",
        "Offline" to "آف لائن",
        "Online" to "آن لائن",
        "Read comments" to "کمنٹس پڑھیں",
        "Views" to "ویوز",
        "View Shop" to "شاپ دیکھیں",
        "Home" to "ہوم",
        "Search" to "تلاش",
        "Messages" to "پیغامات",
        "Notifications" to "اطلاعات",
        "Profile" to "پروفائل",
        "Settings" to "ترتیبات",
        "Settings & Privacy" to "ترتیبات اور رازداری",
        "Admin" to "ایڈمن",
        "Admin Center" to "ایڈمن سینٹر",
        "Logout" to "لاگ آؤٹ",
        "Login" to "لاگ اِن",
        "Sign up" to "اکاؤنٹ بنائیں",
        "Create account" to "اکاؤنٹ بنائیں",
        "People" to "لوگ",
        "Shop" to "شاپ",
        "Shops" to "شاپس",
        "Map" to "نقشہ",
        "Voting" to "ووٹنگ",
        "Announcements" to "اعلانات",
        "For You" to "آپ کے لیے",
        "Following" to "فالو کر رہے ہیں",
        "Followers" to "فالوورز",
        "Shop Posts" to "شاپ پوسٹس",
        "Post" to "پوسٹ",
        "Posts" to "پوسٹس",
        "Saved" to "محفوظ شدہ",
        "All" to "سب",
        "Unread" to "نہ پڑھے گئے",
        "Groups" to "گروپس",
        "Close" to "بند کریں",
        "Cancel" to "منسوخ",
        "Save" to "محفوظ کریں",
        "Delete" to "ڈیلیٹ کریں",
        "Remove" to "ہٹائیں",
        "Refresh" to "تازہ کریں",
        "View" to "دیکھیں",
        "Share" to "شیئر کریں",
        "Message" to "پیغام",
        "Follow" to "فالو کریں",
        "Reply" to "جواب",
        "Send" to "بھیجیں",
        "Select" to "منتخب کریں",
        "Route" to "راستہ",
        "From" to "کہاں سے",
        "To" to "کہاں تک",
        "My location" to "میری لوکیشن",
        "My Location" to "میری لوکیشن",
        "Language" to "زبان",
        "Choose your preferred language" to "اپنی پسندیدہ زبان منتخب کریں",
        "Language preference is saved on this device." to "زبان کی ترجیح اس ڈیوائس پر محفوظ ہو جاتی ہے۔",
        "Privacy" to "رازداری",
        "Safety" to "حفاظت",
        "About" to "تعارف",
        "Phone" to "فون",
        "Email" to "ای میل",
        "City" to "شہر",
        "Village" to "گاؤں",
        "Mohalla" to "محلہ",
        "Address" to "پتہ",
        "Location" to "لوکیشن",
        "Category" to "زمرہ",
        "Description" to "تفصیل",
        "Website" to "ویب سائٹ",
        "Username" to "یوزرنیم",
        "Password" to "پاس ورڈ",
        "Current password" to "موجودہ پاس ورڈ",
        "New password" to "نیا پاس ورڈ",
        "Confirm password" to "پاس ورڈ دوبارہ لکھیں",
        "Full name" to "پورا نام",
        "Email address" to "ای میل ایڈریس",
        "6-digit code" to "6 ہندسوں کا کوڈ",
        "Back" to "واپس",
        "Back to login" to "لاگ اِن پر واپس",
        "Forgot password?" to "پاس ورڈ بھول گئے؟",
        "Already registered? Login" to "پہلے سے اکاؤنٹ ہے؟ لاگ اِن کریں",
        "No account? Create one" to "اکاؤنٹ نہیں؟ نیا بنائیں",
        "Resend Code" to "کوڈ دوبارہ بھیجیں",
        "I agree to the Terms & Conditions and Privacy Policy." to "میں شرائط و ضوابط اور رازداری کی پالیسی سے اتفاق کرتا ہوں۔",
        "Search people, posts, places…" to "لوگ، پوسٹس اور مقامات تلاش کریں…",
        "Search people…" to "لوگ تلاش کریں…",
        "People You May Know" to "آپ شاید ان لوگوں کو جانتے ہوں",
        "Suggested community connections" to "تجویز کردہ مقامی رابطے",
        "People Results" to "لوگوں کے نتائج",
        "Matching people" to "ملتے جلتے لوگ",
        "Load more people" to "مزید لوگ دکھائیں",
        "What's on your mind? Type @ to mention someone" to "آپ کیا سوچ رہے ہیں؟ کسی کو منشن کرنے کے لیے @ لکھیں",
        "Choose a feeling" to "احساس منتخب کریں",
        "Remove feeling" to "احساس ہٹائیں",
        "Mention someone" to "کسی کو منشن کریں",
        "Search name or username" to "نام یا یوزرنیم تلاش کریں",
        "Check in" to "چیک اِن",
        "Use current location" to "موجودہ لوکیشن استعمال کریں",
        "Search a place in Chhachh / Hazro" to "چھچھ / حضرو میں جگہ تلاش کریں",
        "Choose a location from the search results or use current location." to "تلاش کے نتائج سے جگہ منتخب کریں یا موجودہ لوکیشن استعمال کریں۔",
        "Edit post" to "پوسٹ ایڈٹ کریں",
        "Delete post" to "پوسٹ ڈیلیٹ کریں",
        "Report post" to "پوسٹ رپورٹ کریں",
        "Post options" to "پوسٹ کے اختیارات",
        "Send Report" to "رپورٹ بھیجیں",
        "No comments yet." to "ابھی کوئی کمنٹ نہیں۔",
        "People who liked this post" to "اس پوسٹ کو لائک کرنے والے لوگ",
        "Local Shops & Services" to "مقامی شاپس اور خدمات",
        "Discover local businesses." to "قریبی کاروبار تلاش کریں۔",
        "Create one professional shop for your account." to "اپنے اکاؤنٹ کے لیے ایک پروفیشنل شاپ بنائیں۔",
        "Create Shop" to "شاپ بنائیں",
        "Open My Shop" to "میری شاپ کھولیں",
        "My Shop" to "میری شاپ",
        "All Shops" to "تمام شاپس",
        "Shop Details" to "شاپ کی تفصیلات",
        "Shop Suggestions" to "تجویز کردہ شاپس",
        "Local businesses you may want to visit" to "قریبی کاروبار جو آپ دیکھنا چاہیں",
        "Search shops, category or village…" to "شاپ، زمرہ یا گاؤں تلاش کریں…",
        "No shops yet." to "ابھی کوئی شاپ نہیں۔",
        "No shop suggestions right now." to "ابھی کوئی شاپ تجویز موجود نہیں۔",
        "Call" to "کال",
        "Follow Shop" to "شاپ فالو کریں",
        "Share Shop" to "شاپ شیئر کریں",
        "Edit Shop Profile" to "شاپ پروفائل ایڈٹ کریں",
        "Save Shop Profile" to "شاپ پروفائل محفوظ کریں",
        "Upload Photo" to "فوٹو اپلوڈ کریں",
        "Shop profile photo" to "شاپ پروفائل فوٹو",
        "Choose a new photo" to "نئی فوٹو منتخب کریں",
        "Business name" to "شاپ کا نام",
        "Phone (numbers only)" to "فون نمبر (صرف ہندسے)",
        "Phone (+ and digits only)" to "فون (+ اور صرف ہندسے)",
        "WhatsApp (+ and country code)" to "واٹس ایپ (+ اور ملک کا کوڈ)",
        "Shop username" to "شاپ یوزرنیم",
        "Shop Post" to "شاپ پوسٹ",
        "Publish Shop Post" to "شاپ پوسٹ شائع کریں",
        "Photo" to "فوٹو",
        "Everyone" to "سب لوگ",
        "No shop posts yet." to "ابھی کوئی شاپ پوسٹ نہیں ہے۔",
        "Google Maps Location" to "گوگل میپس لوکیشن",
        "Google Maps Location Link" to "گوگل میپس لوکیشن لنک",
        "Edit Shop" to "شاپ ایڈٹ کریں",
        "Delete Shop" to "شاپ ڈیلیٹ کریں",
        "Shop Followers" to "شاپ فالوورز",
        "No followers yet." to "ابھی کوئی فالوور نہیں۔",
        "Business Information" to "کاروباری معلومات",
        "About this shop" to "اس شاپ کے بارے میں",
        "Search conversations…" to "گفتگو تلاش کریں…",
        "New Group" to "نیا گروپ",
        "Create Group" to "گروپ بنائیں",
        "Group name" to "گروپ کا نام",
        "Add members by username, separated with commas." to "یوزرنیم کے ذریعے ممبرز شامل کریں، کوما سے الگ کریں۔",
        "Send a message…" to "پیغام لکھیں…",
        "Send Location" to "لوکیشن بھیجیں",
        "Shared location" to "شیئر کی گئی لوکیشن",
        "Tap a search result to choose a place, or use your current location." to "جگہ منتخب کرنے کے لیے نتیجے پر ٹیپ کریں یا اپنی موجودہ لوکیشن استعمال کریں۔",
        "Make an Announcement" to "اعلان کریں",
        "Record your voice. You can also add a short message or photo." to "اپنی آواز ریکارڈ کریں۔ ساتھ مختصر پیغام یا تصویر بھی شامل کر سکتے ہیں۔",
        "Publish Announcement" to "اعلان شائع کریں",
        "Announcement Comments" to "اعلان کے کمنٹس",
        "Write a comment… Type @ to mention" to "کمنٹ لکھیں… منشن کے لیے @ لکھیں",
        "New Challenge" to "نیا چیلنج",
        "Send Challenge Invite" to "چیلنج دعوت بھیجیں",
        "Accept" to "قبول کریں",
        "Decline" to "رد کریں",
        "Start Match" to "مقابلہ شروع کریں",
        "Cancel Challenge" to "چیلنج منسوخ کریں",
        "Share to Profile" to "پروفائل پر شیئر کریں",
        "Winner" to "فاتح",
        "Your vote" to "آپ کا ووٹ",
        "Vote" to "ووٹ",
        "Chhachh Map" to "چھچھ نقشہ",
        "Chhachh Navigation" to "چھچھ نیویگیشن",
        "Open Navigation" to "نیویگیشن کھولیں",
        "Route to a shop" to "شاپ تک راستہ",
        "Choose Route for directions or View to open the shop" to "راستے کے لیے روٹ منتخب کریں یا شاپ کھولنے کے لیے دیکھیں",
        "No shops have been added yet." to "ابھی کوئی شاپ شامل نہیں کی گئی۔",
        "Find Route draws the route on this map. Open Navigation opens live turn-by-turn directions in Google Maps." to "راستہ تلاش کریں اس نقشے پر روٹ دکھاتا ہے۔ نیویگیشن گوگل میپس میں براہ راست راستہ کھولتی ہے۔",
        "Live conditions for Chhachh" to "چھچھ کا موجودہ موسم",
        "Edit Profile" to "پروفائل ایڈٹ کریں",
        "Edit profile" to "پروفائل ایڈٹ کریں",
        "Save Profile" to "پروفائل محفوظ کریں",
        "View Profile" to "پروفائل دیکھیں",
        "Report profile" to "پروفائل رپورٹ کریں",
        "Report Profile" to "پروفائل رپورٹ کریں",
        "Account & Privacy Settings" to "اکاؤنٹ اور رازداری کی ترتیبات",
        "Basic details" to "بنیادی تفصیلات",
        "Personal details · Optional" to "ذاتی تفصیلات · اختیاری",
        "Social links" to "سوشل لنکس",
        "Phone number" to "فون نمبر",
        "Short bio" to "مختصر تعارف",
        "Work / profession" to "کام / پیشہ",
        "School / college" to "اسکول / کالج",
        "Current city" to "موجودہ شہر",
        "From / hometown" to "آبائی جگہ",
        "Mohalla / area" to "محلہ / علاقہ",
        "Change Password" to "پاس ورڈ تبدیل کریں",
        "Blocked Users" to "بلاک کیے گئے یوزرز",
        "Save Changes" to "تبدیلیاں محفوظ کریں",
        "Allow messages from people" to "لوگوں کے پیغامات کی اجازت دیں",
        "Show current location" to "موجودہ لوکیشن دکھائیں",
        "Identity verification" to "شناخت کی تصدیق",
        "Verification" to "ویریفکیشن",
        "ID Card" to "شناختی کارڈ",
        "Passport" to "پاسپورٹ",
        "Submit Verification" to "ویریفکیشن بھیجیں",
        "Help & Support" to "مدد اور سپورٹ",
        "Contact My Chhachh Support" to "My Chhachh سپورٹ سے رابطہ",
        "Request type" to "درخواست کی قسم",
        "Subject" to "موضوع",
        "Short subject" to "مختصر موضوع",
        "My Support Requests" to "میری سپورٹ درخواستیں",
        "No support requests yet." to "ابھی کوئی سپورٹ درخواست نہیں۔",
        "Waiting for Chhachh Team reply." to "چھچھ ٹیم کے جواب کا انتظار ہے۔",
        "Chhachh Team reply" to "چھچھ ٹیم کا جواب",
        "Delete Account" to "اکاؤنٹ ڈیلیٹ کریں",
        "Permanently remove your account." to "اپنا اکاؤنٹ مستقل طور پر ختم کریں۔",
        "This permanently deletes your account. This action cannot be undone." to "یہ آپ کا اکاؤنٹ مستقل طور پر ڈیلیٹ کرے گا۔ یہ عمل واپس نہیں ہو سکتا۔",
        "Unblock" to "ان بلاک کریں",
        "Admin User Controls" to "ایڈمن یوزر کنٹرولز",
        "Publish as User" to "یوزر کے طور پر شائع کریں",
        "Download Complete PDF" to "مکمل PDF ڈاؤنلوڈ کریں",
        "Activity Audit" to "ایکٹیویٹی ریکارڈ",
        "User Search" to "یوزر تلاش",
        "Users" to "یوزرز",
        "Activity" to "ایکٹیویٹی",
        "Feature Controls" to "فیچر کنٹرول",
        "Admin Profile" to "ایڈمن پروفائل",
        "Admin Post" to "ایڈمن پوسٹ",
        "Search Activity" to "ایکٹیویٹی تلاش کریں",
        "Theme Builder" to "تھیم بلڈر",
        "Complete Theme Control" to "مکمل تھیم کنٹرول",
        "Overview" to "جائزہ",
        "Live website administration" to "لائیو ویب سائٹ انتظام",
        "Live data" to "لائیو ڈیٹا",
        "Refresh" to "تازہ کریں",
        "Search this section…" to "اس حصے میں تلاش کریں…",
        "Open Profile" to "پروفائل کھولیں",
        "Approve" to "منظور کریں",
        "Reject" to "رد کریں",
        "Reports & Support" to "رپورٹس اور سپورٹ",
        "Voting Arena Control" to "ووٹنگ ارینا کنٹرول",
        "Feature Installer" to "فیچر انسٹالر",
        "Ad Manager" to "اشتہار مینیجر",
        "Professional Traffic Meter" to "پروفیشنل ٹریفک میٹر",
        "Save Admin Profile" to "ایڈمن پروفائل محفوظ کریں",
        "Admin Announcement" to "ایڈمن اعلان",
        "Normal Admin Post" to "عام ایڈمن پوسٹ",
        "Publish Admin Post" to "ایڈمن پوسٹ شائع کریں",
        "Reply to Report" to "رپورٹ کا جواب",
        "Send Reply" to "جواب بھیجیں",
        "Send Warning" to "وارننگ بھیجیں",
        "Publish" to "شائع کریں",
        "Delete User" to "یوزر ڈیلیٹ کریں",
        "Delete User Account" to "یوزر اکاؤنٹ ڈیلیٹ کریں",
        "Colors" to "رنگ",
        "Order & Visibility" to "ترتیب اور دکھائی",
        "Save & Apply Complete Theme" to "مکمل تھیم محفوظ اور لاگو کریں",
        "Open Complete Theme Builder" to "مکمل تھیم بلڈر کھولیں",
        "LIVE NOW" to "ابھی لائیو",
        "Show / hide and move" to "دکھائیں / چھپائیں اور منتقل کریں",
        "Retry" to "دوبارہ کوشش",
        "Just now" to "ابھی",
        "Open Location" to "لوکیشن کھولیں",
        "Share Current Location" to "موجودہ لوکیشن شیئر کریں",
        "Location updated with your permission." to "آپ کی اجازت سے لوکیشن محفوظ ہو گئی۔",
        "Location update failed." to "لوکیشن محفوظ نہیں ہو سکی۔",
        "Location permission was denied or unavailable." to "لوکیشن کی اجازت نہیں دی گئی یا دستیاب نہیں۔",
        "Video" to "وڈیو",
        "Photo selected" to "فوٹو منتخب ہو گئی",
        "Video selected" to "وڈیو منتخب ہو گئی"
    )

    fun set(language: String) {
        current = if (language == "ur") "ur" else "en"
    }

    fun translate(value: String): String {
        if (!isUrdu) return value
        val trimmed = value.trim()
        if (trimmed.isEmpty()) return value
        urdu[trimmed]?.let { translated ->
            return value.replace(trimmed, translated)
        }

        return when {
            trimmed.startsWith("Comments ") -> value.replace("Comments ", "کمنٹس ")
            trimmed.startsWith("Likes ") -> value.replace("Likes ", "لائکس ")
            trimmed.startsWith("Blocked Users (") -> value.replace("Blocked Users", "بلاک کیے گئے یوزرز")
            trimmed.startsWith("Shop · ") -> value.replace("Shop · ", "شاپ · ")
            trimmed.startsWith("Gender: ") -> value.replace("Gender: ", "جنس: ")
            trimmed.startsWith("Relationship: ") -> value.replace("Relationship: ", "رشتہ: ")
            trimmed.startsWith("Admin note: ") -> value.replace("Admin note: ", "ایڈمن نوٹ: ")
            trimmed.startsWith("Status: ") -> value.replace("Status: ", "حالت: ")
            trimmed.startsWith("Reason: ") -> value.replace("Reason: ", "وجہ: ")
            trimmed.startsWith("Deleted: ") -> value.replace("Deleted: ", "ڈیلیٹ: ")
            trimmed.endsWith(" total votes") -> value.replace(" total votes", " کل ووٹ")
            trimmed.endsWith(" votes") -> value.replace(" votes", " ووٹ")
            trimmed.contains(" members · ") && trimmed.endsWith(" guests") ->
                value.replace(" members", " ممبرز").replace(" guests", " مہمان")
            else -> value
        }
    }
}

@Composable
fun Text(
    text: String,
    modifier: Modifier = Modifier,
    color: Color = Color.Unspecified,
    fontSize: TextUnit = TextUnit.Unspecified,
    fontStyle: FontStyle? = null,
    fontWeight: FontWeight? = null,
    fontFamily: FontFamily? = null,
    letterSpacing: TextUnit = TextUnit.Unspecified,
    textDecoration: TextDecoration? = null,
    textAlign: TextAlign? = null,
    lineHeight: TextUnit = TextUnit.Unspecified,
    overflow: TextOverflow = TextOverflow.Clip,
    softWrap: Boolean = true,
    maxLines: Int = Int.MAX_VALUE,
    minLines: Int = 1,
    onTextLayout: ((TextLayoutResult) -> Unit)? = null,
    style: TextStyle = LocalTextStyle.current
) {
    MaterialText(
        text = AppLanguage.translate(text),
        modifier = modifier,
        color = color,
        fontSize = fontSize,
        fontStyle = fontStyle,
        fontWeight = fontWeight,
        fontFamily = fontFamily,
        letterSpacing = letterSpacing,
        textDecoration = textDecoration,
        textAlign = textAlign,
        lineHeight = lineHeight,
        overflow = overflow,
        softWrap = softWrap,
        maxLines = maxLines,
        minLines = minLines,
        onTextLayout = onTextLayout,
        style = style
    )
}
